name = "yevi"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true

[vars]
PROXYIP = "165.154.29.90"
UUID = "6c47a23e-d580-4e75-b896-652f764ae9ae"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
